# Generated by Django 5.2.4 on 2025-08-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_agency",
            field=models.BooleanField(default=False),
        ),
    ]
